import { z } from 'zod';
import type { TransactionInput } from '../domain/types';
const amount = z.coerce.number().int().safe(),
  id = z.string(),
  nullable = id.nullable();
export const transactionInputSchema = z.object({
  type: z.enum(['income', 'expense', 'transfer']),
  amount,
  wallet_id: id,
  destination_wallet_id: nullable,
  transaction_actor: id,
  transaction_scope: z.enum(['personal', 'family']),
  scope_member_id: nullable,
  status: z.enum(['pending', 'completed', 'cancelled']),
  occurred_at: z.string(),
  category_id: nullable,
  merchant: z.string(),
  notes: z.string(),
  fee_amount: amount,
  splits: z.array(z.object({ category_id: id, amount })).optional(),
  tag_ids: z.array(id).optional(),
}) satisfies z.ZodType<TransactionInput>;
export const snapshotSchema = z.object({
  household: z.object({
    id,
    name: z.string(),
    attachment_retention: z.string(),
    session_lock_minutes: z.number(),
  }),
  members: z.array(
    z.object({
      user_id: id,
      household_id: id,
      role: z.enum(['owner', 'member']),
      display_name: z.string(),
      active: z.boolean().default(true),
    }),
  ),
  wallets: z.array(
    z.object({
      id,
      household_id: id,
      name: z.string(),
      type: z.enum(['bank', 'cash', 'e_wallet']),
      ownership: z.enum(['personal', 'shared']),
      wallet_owner: nullable,
      initial_balance: amount,
      active: z.boolean(),
      icon: z.string().default('wallet'),
      color: z.string().default('#164c3e'),
      account_identifier: z.string().nullable().default(null),
      version: z.number().int().positive().default(1),
    }),
  ),
  transactions: z.array(
    z.object({
      id,
      household_id: id,
      type: z.enum(['income', 'expense', 'transfer']),
      amount,
      wallet_id: id,
      destination_wallet_id: nullable,
      transaction_actor: id,
      transaction_scope: z.enum(['personal', 'family']),
      scope_member_id: nullable,
      status: z.enum(['pending', 'completed', 'cancelled']),
      occurred_at: z.string(),
      category_id: nullable,
      merchant: z.string(),
      notes: z.string(),
      created_by: id,
      deleted_at: nullable,
      parent_transaction_id: nullable.optional(),
      source: z.string().optional(),
      recurring_template_id: nullable.optional(),
      version: z.number().int().positive().default(1),
    }),
  ),
  categories: z.array(
    z.object({
      id,
      name: z.string(),
      parent_id: nullable,
      kind: z.enum(['income', 'expense', 'both']),
      color: z.string().default('#86b49c'),
      icon: z.string().default('tag'),
      sort_order: z.number().int().default(0),
    }),
  ),
  tags: z.array(z.object({ id, name: z.string() })).default([]),
  transactionTags: z.array(z.object({ transaction_id: id, tag_id: id })).default([]),
  splits: z.array(z.object({ transaction_id: id, category_id: id, amount })),
  budgets: z.array(
    z.object({
      id,
      name: z.string(),
      category_id: nullable,
      wallet_id: nullable,
      amount,
      start_date: z.string(),
      end_date: z.string(),
      rollover: z.enum(['reset', 'rollover']),
      rollover_amount: amount,
      warning_thresholds: z.array(z.number()),
      active: z.boolean().default(true),
      cadence: z.enum(['weekly', 'monthly', 'custom']).default('custom'),
      auto_continue: z.boolean().default(false),
      predecessor_id: nullable.optional(),
      closed_at: nullable.optional(),
      closed_spent: amount.nullable().optional(),
      automation_error: nullable.optional(),
    }),
  ),
  goals: z.array(
    z.object({
      id,
      title: z.string(),
      target_amount: amount,
      deadline: nullable,
      saved: amount,
      notes: z.string().default(''),
      status: z.enum(['active', 'completed', 'archived']).default('active'),
    }),
  ),
  contributions: z
    .array(z.object({ id, goal_id: id, amount, created_by: id, contributed_at: z.string() }))
    .default([]),
  recurring: z
    .array(
      z.object({
        id,
        household_id: id,
        created_by: id,
        name: z.string(),
        mode: z.enum(['ask', 'auto_create']),
        cadence: z.enum(['weekly', 'monthly']),
        anchor_date: z.string(),
        next_run: z.string(),
        end_date: nullable,
        run_time: z.string(),
        active: z.boolean(),
        occurrence_index: z.number().int(),
        version: z.number().int(),
        transaction_template: transactionInputSchema,
      }),
    )
    .default([]),
  occurrences: z
    .array(
      z.object({
        id,
        household_id: id,
        template_id: id,
        scheduled_date: z.string(),
        status: z.enum(['pending', 'created', 'skipped', 'error']),
        input: transactionInputSchema,
        transaction_id: nullable,
        error_reason: z.string().nullable(),
      }),
    )
    .default([]),
});
