import {
  LayoutDashboard,
  ArrowLeftRight,
  Wallet,
  ChartPie,
  Target,
  Trash2,
  Settings,
  Plus,
  Search,
  Eye,
  EyeOff,
  Sparkles,
  ArrowDownLeft,
  ArrowUpRight,
  X,
  LogOut,
  Check,
  LockKeyhole,
  Landmark,
  ArrowRight,
  Menu,
  ChevronRight,
  ChevronDown,
  ChevronLeft,
  CalendarDays,
  Clock3,
  Pencil,
  History,
  Upload,
  Tag,
  Copy,
  Camera,
  UserRound,
  type LucideProps,
} from 'lucide-react';
const icons = {
  user: UserRound,
  camera: Camera,
  calendar: CalendarDays,
  clock: Clock3,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  dashboard: LayoutDashboard,
  transfer: ArrowLeftRight,
  wallet: Wallet,
  budget: ChartPie,
  goal: Target,
  trash: Trash2,
  settings: Settings,
  plus: Plus,
  search: Search,
  eye: Eye,
  eyeOff: EyeOff,
  sparkle: Sparkles,
  income: ArrowDownLeft,
  expense: ArrowUpRight,
  close: X,
  logout: LogOut,
  check: Check,
  lock: LockKeyhole,
  bank: Landmark,
  arrowRight: ArrowRight,
  menu: Menu,
  chevronRight: ChevronRight,
  edit: Pencil,
  history: History,
  upload: Upload,
  tag: Tag,
  copy: Copy,
} as const;
export type IconName = keyof typeof icons;
export function Icon({ name, ...props }: LucideProps & { name: IconName }) {
  const Component = icons[name];
  return <Component size={20} strokeWidth={1.7} aria-hidden="true" focusable="false" {...props} />;
}
